site_name: Sons of PHP - Documentation
site_url: https://docs.sonsofphp.com/
copyright: Copyright &copy 2022 Sons of PHP
repo_url: https://github.com/SonsOfPHP/sonsofphp
repo_name: Mother Repository
edit_uri: https://github.com/SonsOfPHP/sonsofphp-docs/edit/main/docs/
theme:
    name: material
    features:
        #- navigation.instant
        #- navigation.tabs
        #- navigation.sections
        - navigation.top
    icon:
        repo: fontawesome/brands/github
plugins:
    - search
extra:
    generator: false
    #version:
    #    provider: mike
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/SonsOfPHP
          name: Sons of PHP on GitHub
#nav:
#    #- index.md
#    - Clock:
#        - clock/index.md
#    - CQRS:
#        - cqrs/index.md
#    - Event Dispatcher:
#        - event-dispatcher/index.md
#    - Event Sourcing:
#        - event-sourcing/index.md
#    - Feature Toggle:
#        - feature-toggle/index.md
#    - JSON:
#        - json/index.md
#    - Money:
#        - money/index.md
